apiVersion: v1
kind: Secret
metadata:
  name: suratech-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "usersura"
  SPRING_DATASOURCE_PASSWORD: "root"
  AZURE_SERVICEBUS_CONNECTION_STRING: "URL_AZURE_SERVICEBUS"