apiVersion: v1
kind: Service
metadata:
  name: suratech
  labels:
    app: suratech
spec:
  selector:
    app: suratech
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP